### ISSUE TITLE
Unknown class

### ISSUE THREAD

**Issue by whyygug** [sjg02122/MonoFormer#1]
Congratulations on your work, I got some trouble when using the code.

I run this script: 
`python3 scripts/infer.py --checkpoint weights/monoformer_hybrid.ckpt --input my_images --output output_dir`
But got this:

### Preparing Model
Model: 
Traceback (most recent call last):
  File "scripts/infer.py", line 174, in <module>
    main(args)
  File "scripts/infer.py", line 142, in main
    model_wrapper = ModelWrapper(config, load_datasets=False)
  File "/home/myname/MonoFormer-main/monoformer/models/model_wrapper.py", line 58, in __init__
    self.prepare_model(resume)
  File "/home/myname/MonoFormer-main/monoformer/models/model_wrapper.py", line 73, in prepare_model
    self.model = setup_model(self.config.model, self.config.prepared)
  File "/home/myname/MonoFormer-main/monoformer/models/model_wrapper.py", line 458, in setup_model
    model = load_class(config.name, paths=['monoformer.models',])(
  File "/home/myname/MonoFormer-main/monoformer/utils/load.py", line 107, in load_class
    raise ValueError('Unknown class {}'.format(filename))
ValueError: Unknown class 

It seems that the code has correctly found the `.ckpt` file, but fail to initial the corresponding model. Can you help me to figure it out? Thanks.

**Comment by sjg02122** [comment]
Thank you for your interest in our work.
Could you show the printing of 'filename' in the error situation?

**Comment by whyygug** [comment]
Thanks for your timely response.  
It seems that the string `filename` is empty and does not produce any prints.

![fm](https://user-images.githubusercontent.com/31730585/228461116-84094c7c-5f8a-4022-a5c9-347b1830e0b2.PNG)

**Comment by sjg02122** [comment]
This problem has never happened to me. 
I recommend a solution by debugging by code.
I wish you the best of luck.

**Comment by Ayews** [comment]
try ` python3 scripts/infer.py --checkpoint 'weights/monoformer_hybrid.ckpt' --input my_images --output output_dir --config 'configs/train_kitti_hybrid.yaml'`
