### ISSUE TITLE
About the evaluation with other datasets

### ISSUE THREAD

**Issue by Byeongjun1022** [sjg02122/MonoFormer#2]
Thanks for providing the result of the research and code.

Do you have the plan for providing the evaluation code  for other datasets like ETH3D, DeMoN (e.g., MVS, SUN3D, RGBD, Scenes11) and generated texture-shifted datasets?
Also, Do you have plan for providing the methods for generating the evaluation datasets with same condition?

**Comment by sjg02122** [comment]
Thank you for your interest.

1. The method of data generation is described in detail in the appendix of the paper. You can make it with a simple opencv code.

2. For the evaluation code, usethe same code as the KITTI evaluation code. If you want to know detail, please refer to the following link.
https://github.com/TRI-ML/DDAD
